apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: go-sgkmwqqv 
  janus-idp.io/tekton: go-sgkmwqqv
  backstage.io/kubernetes-id: go-sgkmwqqv
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-sgkmwqqv
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml