apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-sgkmwqqv-gitops
  description: This is GitOps manifest for go-sgkmwqqv   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=go-sgkmwqqv
    backstage.io/kubernetes-id: go-sgkmwqqv 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-sgkmwqqv
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-sgkmwqqv
