apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-sgkmwqqv
  janus-idp.io/tekton: go-sgkmwqqv
  backstage.io/kubernetes-id: go-sgkmwqqv
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-sgkmwqqv
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
